name: C# Code Analysis with OpenAI

on:
  push:
    branches:
      - master
    paths:
      - '**/*.cs'

jobs:
  analyze-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Analyze C# code with OpenAI
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          files=$(find . -type f -name '*.cs' -not -path "./obj/*" -not -path "./bin/*")
          for file in $files; do
            echo "Analyzing $file"
            
            # Подготовка содержимого файла для запроса
            content=$(cat "$file" | base64 | tr -d '\n')
            prompt="Analyze this C# code:\\n\\n$content\\n\\n###"
            
            # Сохранение JSON запроса во временный файл
            echo "{\"model\": \"text-davinci-003\", \"prompt\": \"$prompt\", \"temperature\": 0.5, \"max_tokens\": 2048}" > temp_request.json
            
            # Выполнение запроса к OpenAI API
            response=$(curl -s -X POST "https://api.openai.com/v4/completions" \
              -H "Authorization: Bearer $OPENAI_API_KEY" \
              -H "Content-Type: application/json" \
              -d @temp_request.json)
              
            # Вывод ответа от OpenAI
            echo "Response from OpenAI for $file:"
            echo "$response" | jq '.choices[0].text' || echo "Failed to get a valid response"
            echo "-----------------------------------"
            
            # Удаление временного файла
            rm temp_request.json
          done
        shell: bash
