name: C# Code Analysis with OpenAI

on:
  push:
    branches:
      - master # Запуск workflow на push в ветку master
    paths:
      - '**/*.cs' # Фокусируемся на изменениях в файлах C#

jobs:
  analyze-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Analyze C# code with OpenAI
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          files=$(find . -type f -name '*.cs' -not -path "./obj/*" -not -path "./bin/*")
          for file in $files; do
            echo "Analyzing $file"
            content=$(cat "$file" | base64) # Кодирование содержимого файла в base64 для упрощения передачи
            prompt="Analyze this C# code:\n\n$(echo $content | base64 --decode)\n\n###"
            
            response=$(curl -s -X POST "https://api.openai.com/v4/completions" \
              -H "Authorization: Bearer $OPENAI_API_KEY" \
              -H "Content-Type: application/json" \
              -d "{\"model\": \"code-davinci-002\", \"prompt\": \"$prompt\", \"temperature\": 0.5, \"max_tokens\": 150}")
              
            echo "Response from OpenAI for $file:"
            echo $response | jq '.choices[0].text'
            echo "-----------------------------------"
          done
        shell: bash
