name: Code Analysis with OpenAI

on:
  push:
    branches:
      - main
    paths:
      - '**/*.py' # Пример для Python файлов, измените маску пути в соответствии с вашими нуждами

jobs:
  analyze-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Analyze code with OpenAI
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          for file in $(find . -name '*.py'); do # Пример для Python файлов
            content=$(cat $file)
            response=$(curl -s -X POST "https://api.openai.com/v4/completions" \
              -H "Authorization: Bearer $OPENAI_API_KEY" \
              -H "Content-Type: application/json" \
              -d "{\"model\": \"code-davinci-002\", \"prompt\": \"### Analyze this code\\n\\n\`\`\`python\\n$content\\n\`\`\`\\n\", \"temperature\": 0.5, \"max_tokens\": 150}")
            echo "File: $file"
            echo "Response: $response"
            echo "-----------------------------------"
          done
        shell: bash
