name: C# Code Analysis with OpenAI on Changed Files Only

on:
  push:
    branches:
      - main
    paths:
      - '**/*.cs'

jobs:
  analyze-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install jq
        run: sudo apt-get install jq
      
      - name: Get list of changed .cs files
        id: get-changed-files
        run: |
          echo "Changed files in this commit:"
          git diff --name-only ${{ github.sha }} ${{ github.event.before }} | grep '\.cs$' > changed_files.txt
          if [ -s changed_files.txt ]; then
            echo "::set-output name=files::$(<changed_files.txt)"
          else
            echo "::set-output name=files::"
          fi
      
      - name: Analyze changed C# files with OpenAI
        if: steps.get-changed-files.outputs.files != ''
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          while IFS= read -r file; do
            echo "Analyzing $file"
            content=$(base64 "$file")
            prompt="Analyze this C# code:\n\n$(echo $content | base64 --decode)\n\n###"
            response=$(curl -s -X POST "https://api.openai.com/v4/completions" \
              -H "Authorization: Bearer $OPENAI_API_KEY" \
              -H "Content-Type: application/json" \
              -d "{\"model\": \"code-davinci-002\", \"prompt\": \"$prompt\", \"temperature\": 0.7, \"max_tokens\": 2048}")
            echo "Response: $response"
            echo "-----------------------------------"
          done < changed_files.txt
