name: C# Code Analysis with OpenAI

on:
  push:
    branches:
      - master # Или ваша целевая ветка
    paths:
      - '**/*.cs' # Паттерн для поиска файлов C#

jobs:
  analyze-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Analyze C# code with OpenAI
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          find . -type f -name '*.cs' -not -path "./obj/*" -not -path "./bin/*" | while read file; do
            echo "Analyzing $file"
            
            # Кодирование содержимого файла в формате Base64 для избежания проблем с переносами строк и специальными символами
            content=$(base64 "$file")
            
            # Создание временного файла для тела запроса
            request_body=$(mktemp)
            echo "{\"model\": \"code-davinci-002\", \"prompt\": \"Analyze this C# code:\\n\\n$(echo $content | base64 --decode)\\n\", \"temperature\": 0.7, \"max_tokens\": 2048}" > "$request_body"
            
            # Выполнение запроса к OpenAI
            response=$(curl -s -X POST "https://api.openai.com/v4/completions" \
              -H "Authorization: Bearer $OPENAI_API_KEY" \
              -H "Content-Type: application/json" \
              -d @"$request_body")
              
            echo "Response for $file: $response"
            
            # Удаление временного файла запроса
            rm "$request_body"
            
            echo "-----------------------------------"
          done
