name: C# Code Analysis with OpenAI

on:
  push:
    branches:
      - master # Запуск workflow на push в ветку master
    paths:
      - '**/*.cs' # Фокусируемся на изменениях в файлах C#

jobs:
  analyze-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # Обновлено до последней версии
      
      # Здесь можете добавить шаги для установки или настройки Node.js, если это необходимо для вашего workflow
      
      - name: Analyze C# code with OpenAI
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          # Скрипт для анализа кода
